# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputFileNameWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inputFileNameWindow(object):
    def setupUi(self, inputFileNameWindow):
        inputFileNameWindow.setObjectName("inputFileNameWindow")
        inputFileNameWindow.setWindowModality(QtCore.Qt.NonModal)
        inputFileNameWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        inputFileNameWindow.setFont(font)
        inputFileNameWindow.setStyleSheet("background-color: rgb(212, 237, 255);")
        self.centralwidget = QtWidgets.QWidget(inputFileNameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.continueButton = QtWidgets.QPushButton(self.centralwidget)
        self.continueButton.setGeometry(QtCore.QRect(300, 350, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.continueButton.setFont(font)
        self.continueButton.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.continueButton.setDefault(False)
        self.continueButton.setFlat(False)
        self.continueButton.setObjectName("continueButton")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(0, 200, 800, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.infoLabel.setFont(font)
        self.infoLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.infoLabel.setAutoFillBackground(False)
        self.infoLabel.setStyleSheet("")
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setWordWrap(False)
        self.infoLabel.setObjectName("infoLabel")
        self.fileNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileNameLineEdit.setGeometry(QtCore.QRect(150, 280, 500, 45))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.fileNameLineEdit.setFont(font)
        self.fileNameLineEdit.setObjectName("fileNameLineEdit")
        inputFileNameWindow.setCentralWidget(self.centralwidget)

        def createFile():
            from InputTest import fileNameTest
            fileNameTest(self.fileNameLineEdit.text())

        self.continueButton.clicked.connect(createFile)

        self.retranslateUi(inputFileNameWindow)
        QtCore.QMetaObject.connectSlotsByName(inputFileNameWindow)

    def retranslateUi(self, inputFileNameWindow):
        _translate = QtCore.QCoreApplication.translate
        inputFileNameWindow.setWindowTitle(_translate("inputFileNameWindow", "Experiment"))
        self.label.setText(_translate("inputFileNameWindow", "Создание документа"))
        self.continueButton.setText(_translate("inputFileNameWindow", "Продолжить"))
        self.infoLabel.setText(_translate("inputFileNameWindow", "Ведите название создаваемого файла:"))
        self.fileNameLineEdit.setPlaceholderText(_translate("inputFileNameWindow", "Пример: example"))


def showInputFileNameWindow():
    global inputFileNameWindow
    inputFileNameWindow = QtWidgets.QMainWindow()
    ui = Ui_inputFileNameWindow()
    ui.setupUi(inputFileNameWindow)
    inputFileNameWindow.show()


def editCheckedList(data):
    global checkedList
    checkedList = data
    showInputFileNameWindow()


def closeInputFileNameWindow():
    inputFileNameWindow.close()


# from Windows.QtWindows.inputFileNameWindow import editNameUser
# editNameUser("Здравствуйте, " + ''.join(user[1]))
# from Windows.QtWindows.inputFileNameWindow import showInputFileNameWindow
# showInputFileNameWindow()

