# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputFileFormatting.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inputFileFormattingWindow(object):
    def setupUi(self, inputFileFormattingWindow):
        inputFileFormattingWindow.setObjectName("inputFileFormattingWindow")
        inputFileFormattingWindow.setWindowModality(QtCore.Qt.NonModal)
        inputFileFormattingWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        inputFileFormattingWindow.setFont(font)
        inputFileFormattingWindow.setStyleSheet("background-color: rgb(212, 237, 255);")
        self.centralwidget = QtWidgets.QWidget(inputFileFormattingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.continueButton = QtWidgets.QPushButton(self.centralwidget)
        self.continueButton.setGeometry(QtCore.QRect(300, 350, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.continueButton.setFont(font)
        self.continueButton.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.continueButton.setDefault(False)
        self.continueButton.setFlat(False)
        self.continueButton.setObjectName("continueButton")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(0, 200, 800, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.infoLabel.setFont(font)
        self.infoLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.infoLabel.setAutoFillBackground(False)
        self.infoLabel.setStyleSheet("")
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setWordWrap(False)
        self.infoLabel.setObjectName("infoLabel")
        self.fileFormattingComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.fileFormattingComboBox.setGeometry(QtCore.QRect(200, 280, 400, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.fileFormattingComboBox.setFont(font)
        self.fileFormattingComboBox.setObjectName("fileFormattingComboBox")
        inputFileFormattingWindow.setCentralWidget(self.centralwidget)

        from WorkWithDB import findFileFormattingPattern
        patternArr = findFileFormattingPattern()
        for i in range(len(patternArr)):
            self.fileFormattingComboBox.addItem(patternArr[i][1])

        def continueCreateFile():
            for i in range(len(patternArr)):
                if self.fileFormattingComboBox.currentText() == patternArr[i][1]:
                    from InputTest import editFileFormatting
                    editFileFormatting(patternArr[i][0])
                    from Windows.QtWindows.inputFileNameWindow import showInputFileNameWindow
                    showInputFileNameWindow()
                    closeInputFileFormattingWindow()

        self.continueButton.clicked.connect(continueCreateFile)

        self.retranslateUi(inputFileFormattingWindow)
        QtCore.QMetaObject.connectSlotsByName(inputFileFormattingWindow)

    def retranslateUi(self, inputFileFormattingWindow):
        _translate = QtCore.QCoreApplication.translate
        inputFileFormattingWindow.setWindowTitle(_translate("inputFileFormattingWindow", "Experiment"))
        self.label.setText(_translate("inputFileFormattingWindow", "Создание документа"))
        self.continueButton.setText(_translate("inputFileFormattingWindow", "Продолжить"))
        self.infoLabel.setText(_translate("inputFileFormattingWindow", "Выберете форматирование создаваемого файла:"))


def showInputFileFormattingWindow():
    global inputFileFormattingWindow
    inputFileFormattingWindow = QtWidgets.QMainWindow()
    ui = Ui_inputFileFormattingWindow()
    ui.setupUi(inputFileFormattingWindow)
    inputFileFormattingWindow.show()


def closeInputFileFormattingWindow():
    inputFileFormattingWindow.close()
