# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputParamToDB.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cryptocode

from PyQt5 import QtCore, QtGui, QtWidgets

from Windows.QtWindows.errWindow import showErrWindow, editText
from InputTest import generateRandomString


class Ui_inputParamToDBWindow(object):
    def setupUi(self, inputParamToDBWindow):
        inputParamToDBWindow.setObjectName("inputParamToDBWindow")
        inputParamToDBWindow.setWindowModality(QtCore.Qt.NonModal)
        inputParamToDBWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        inputParamToDBWindow.setFont(font)
        inputParamToDBWindow.setStyleSheet("background-color: rgb(212, 237, 255);")
        self.centralwidget = QtWidgets.QWidget(inputParamToDBWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.Label1 = QtWidgets.QLabel(self.centralwidget)
        self.Label1.setGeometry(QtCore.QRect(200, 120, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label1.setFont(font)
        self.Label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label1.setAutoFillBackground(False)
        self.Label1.setStyleSheet("")
        self.Label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label1.setWordWrap(False)
        self.Label1.setObjectName("Label1")
        self.Label2 = QtWidgets.QLabel(self.centralwidget)
        self.Label2.setGeometry(QtCore.QRect(200, 200, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label2.setFont(font)
        self.Label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label2.setAutoFillBackground(False)
        self.Label2.setStyleSheet("")
        self.Label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label2.setWordWrap(False)
        self.Label2.setObjectName("Label2")
        self.inputButton = QtWidgets.QPushButton(self.centralwidget)
        self.inputButton.setGeometry(QtCore.QRect(300, 530, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.inputButton.setFont(font)
        self.inputButton.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.inputButton.setDefault(False)
        self.inputButton.setFlat(False)
        self.inputButton.setObjectName("inputButton")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(200, 240, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.passwordLineEdit.setTabletTracking(True)
        self.passwordLineEdit.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.nameUserLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameUserLineEdit.setGeometry(QtCore.QRect(200, 160, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nameUserLineEdit.setFont(font)
        self.nameUserLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nameUserLineEdit.setTabletTracking(True)
        self.nameUserLineEdit.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.nameUserLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.nameUserLineEdit.setObjectName("nameUserLineEdit")
        self.Label3 = QtWidgets.QLabel(self.centralwidget)
        self.Label3.setGeometry(QtCore.QRect(200, 280, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label3.setFont(font)
        self.Label3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label3.setAutoFillBackground(False)
        self.Label3.setStyleSheet("")
        self.Label3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label3.setWordWrap(False)
        self.Label3.setObjectName("Label3")
        self.nameDBEditTwo = QtWidgets.QLineEdit(self.centralwidget)
        self.nameDBEditTwo.setGeometry(QtCore.QRect(200, 320, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nameDBEditTwo.setFont(font)
        self.nameDBEditTwo.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nameDBEditTwo.setTabletTracking(True)
        self.nameDBEditTwo.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.nameDBEditTwo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.nameDBEditTwo.setObjectName("nameDBEditTwo")
        self.passwordLineEditTwo_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLineEditTwo_2.setGeometry(QtCore.QRect(200, 400, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.passwordLineEditTwo_2.setFont(font)
        self.passwordLineEditTwo_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.passwordLineEditTwo_2.setTabletTracking(True)
        self.passwordLineEditTwo_2.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.passwordLineEditTwo_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.passwordLineEditTwo_2.setObjectName("passwordLineEditTwo_2")
        self.Label4 = QtWidgets.QLabel(self.centralwidget)
        self.Label4.setGeometry(QtCore.QRect(200, 360, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label4.setFont(font)
        self.Label4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label4.setAutoFillBackground(False)
        self.Label4.setStyleSheet("")
        self.Label4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label4.setWordWrap(False)
        self.Label4.setObjectName("Label4")
        self.passwordLineEditTwo_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLineEditTwo_3.setGeometry(QtCore.QRect(200, 480, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.passwordLineEditTwo_3.setFont(font)
        self.passwordLineEditTwo_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.passwordLineEditTwo_3.setTabletTracking(True)
        self.passwordLineEditTwo_3.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.passwordLineEditTwo_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.passwordLineEditTwo_3.setObjectName("passwordLineEditTwo_3")
        self.Label5 = QtWidgets.QLabel(self.centralwidget)
        self.Label5.setGeometry(QtCore.QRect(200, 440, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label5.setFont(font)
        self.Label5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label5.setAutoFillBackground(False)
        self.Label5.setStyleSheet("")
        self.Label5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label5.setWordWrap(False)
        self.Label5.setObjectName("Label5")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(20, 20, 130, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(200, 220, 210);")
        self.backButton.setDefault(False)
        self.backButton.setFlat(False)
        self.backButton.setObjectName("backButton")
        inputParamToDBWindow.setCentralWidget(self.centralwidget)

        def showBackWindow():
            from Windows.QtWindows.mainWindow import showMainWindow
            showMainWindow()
            closeInputParamToDBWindow()

        def inputParamTest():
            if len(self.nameUserLineEdit.text()) != 0:
                if len(self.passwordLineEdit.text()) != 0:
                    if len(self.nameDBEditTwo.text()) != 0:
                        if len(self.passwordLineEditTwo_2.text()) != 0:
                            if len(self.passwordLineEditTwo_3.text()) != 0:
                                tryToSaveParamConnectToDB(self.nameUserLineEdit.text(),
                                                          self.passwordLineEdit.text(),
                                                          self.nameDBEditTwo.text(),
                                                          self.passwordLineEditTwo_2.text(),
                                                          self.passwordLineEditTwo_3.text())
                            else:
                                editText("Ошибка! Вы не ввели порт")
                                showErrWindow()
                        else:
                            editText("Ошибка! Вы не ввели хост")
                            showErrWindow()
                    else:
                        editText("Ошибка! Вы не ввели имя базы данных")
                        showErrWindow()
                else:
                    editText("Ошибка! Вы не ввели пароль")
                    showErrWindow()
            else:
                editText("Ошибка! Вы не ввели имя пользователя")
                showErrWindow()

        self.backButton.clicked.connect(showBackWindow)
        self.inputButton.clicked.connect(inputParamTest)

        self.retranslateUi(inputParamToDBWindow)
        QtCore.QMetaObject.connectSlotsByName(inputParamToDBWindow)

    def retranslateUi(self, inputParamToDBWindow):
        _translate = QtCore.QCoreApplication.translate
        inputParamToDBWindow.setWindowTitle(_translate("inputParamToDBWindow", "Experiment"))
        self.label.setText(_translate("inputParamToDBWindow", "Параметры входа в БД"))
        self.Label1.setText(_translate("inputParamToDBWindow", "Введите имя пользователя:"))
        self.Label2.setText(_translate("inputParamToDBWindow", "Введите пароль:"))
        self.inputButton.setText(_translate("inputParamToDBWindow", "Далее"))
        self.passwordLineEdit.setPlaceholderText(_translate("inputParamToDBWindow", "Пример: 12345678"))
        self.nameUserLineEdit.setPlaceholderText(_translate("inputParamToDBWindow", "Пример: nik"))
        self.Label3.setText(_translate("inputParamToDBWindow", "Введите имя БД:"))
        self.nameDBEditTwo.setPlaceholderText(_translate("inputParamToDBWindow", "Пример: document_creation_support"))
        self.passwordLineEditTwo_2.setPlaceholderText(_translate("inputParamToDBWindow", "Пример: 192.168.56.50"))
        self.Label4.setText(_translate("inputParamToDBWindow", "Введите хост:"))
        self.passwordLineEditTwo_3.setPlaceholderText(_translate("inputParamToDBWindow", "Пример: 5432"))
        self.Label5.setText(_translate("inputParamToDBWindow", "Введите порт:"))
        self.backButton.setText(_translate("inputParamToDBWindow", "Назад"))


def showInputParamToDBWindow():
    global inputParamToDBWindow
    inputParamToDBWindow = QtWidgets.QMainWindow()
    ui = Ui_inputParamToDBWindow()
    ui.setupUi(inputParamToDBWindow)
    inputParamToDBWindow.show()


def closeInputParamToDBWindow():
    inputParamToDBWindow.close()


def tryToSaveParamConnectToDB(nameUser, password, nameDB, host, port):
    cryptoKey = generateRandomString(100)
    docOutput = open("config.txt", "w")
    docOutput.write(str(cryptoKey) + "\n" +
                    str(cryptocode.encrypt(nameUser, cryptoKey)) + "\n" +
                    str(cryptocode.encrypt(password, cryptoKey)) + "\n" +
                    str(cryptocode.encrypt(nameDB, cryptoKey)) + "\n" +
                    str(cryptocode.encrypt(host, cryptoKey)) + "\n" +
                    str(cryptocode.encrypt(port, cryptoKey)) + "\n")
    docOutput.close()
    editText("Параметры подключения успешно сохранены!")
    showErrWindow()
    closeInputParamToDBWindow()
    from Windows.QtWindows.mainWindow import showMainWindow
    showMainWindow()
