# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os.path
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(212, 237, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.phoneNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.phoneNumberLabel.setGeometry(QtCore.QRect(170, 170, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.phoneNumberLabel.setFont(font)
        self.phoneNumberLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phoneNumberLabel.setAutoFillBackground(False)
        self.phoneNumberLabel.setStyleSheet("")
        self.phoneNumberLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phoneNumberLabel.setWordWrap(False)
        self.phoneNumberLabel.setObjectName("phoneNumberLabel")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(170, 310, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passwordLabel.setAutoFillBackground(False)
        self.passwordLabel.setStyleSheet("")
        self.passwordLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setWordWrap(False)
        self.passwordLabel.setObjectName("passwordLabel")
        self.inputButton = QtWidgets.QPushButton(self.centralwidget)
        self.inputButton.setGeometry(QtCore.QRect(300, 470, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.inputButton.setFont(font)
        self.inputButton.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.inputButton.setDefault(False)
        self.inputButton.setFlat(False)
        self.inputButton.setObjectName("inputButton")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(170, 380, 460, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.passwordLineEdit.setTabletTracking(True)
        self.passwordLineEdit.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.phoneNumberLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneNumberLineEdit.setGeometry(QtCore.QRect(170, 240, 460, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.phoneNumberLineEdit.setFont(font)
        self.phoneNumberLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.phoneNumberLineEdit.setTabletTracking(True)
        self.phoneNumberLineEdit.setStyleSheet("border-color: rgb(0, 85, 0);")
        self.phoneNumberLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.phoneNumberLineEdit.setObjectName("phoneNumberLineEdit")
        self.editPasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.editPasswordButton.setGeometry(QtCore.QRect(320, 540, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.editPasswordButton.setFont(font)
        self.editPasswordButton.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.editPasswordButton.setDefault(False)
        self.editPasswordButton.setFlat(False)
        self.editPasswordButton.setObjectName("editPasswordButton")
        self.paramConnectToDBButton = QtWidgets.QPushButton(self.centralwidget)
        self.paramConnectToDBButton.setGeometry(QtCore.QRect(660, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.paramConnectToDBButton.setFont(font)
        self.paramConnectToDBButton.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.paramConnectToDBButton.setDefault(False)
        self.paramConnectToDBButton.setFlat(False)
        self.paramConnectToDBButton.setObjectName("paramConnectToDBButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        if os.path.exists('config.txt'):
            self.inputButton.clicked.connect(
                lambda: userTest(self.phoneNumberLineEdit.text(), self.passwordLineEdit.text()))
            self.inputButton.setAutoDefault(True)
            self.phoneNumberLineEdit.returnPressed.connect(self.inputButton.click)
            self.passwordLineEdit.returnPressed.connect(self.inputButton.click)

            self.editPasswordButton.clicked.connect(editPassword)
        else:
            from Windows.QtWindows.errWindow import editText, showErrWindow
            editText("Ошибка! Пожалуйста укажите параметры подключения к БД во вкладке \"Параметры\"")
            showErrWindow()

        self.paramConnectToDBButton.clicked.connect(editParamConnectToDB)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Experiment"))
        self.label.setText(_translate("MainWindow", "Вход"))
        self.phoneNumberLabel.setText(_translate("MainWindow", "Введите номер телефона:"))
        self.passwordLabel.setText(_translate("MainWindow", "Введите пароль:"))
        self.inputButton.setText(_translate("MainWindow", "Войти"))
        self.passwordLineEdit.setPlaceholderText(_translate("MainWindow", "Пример: 1234"))
        self.phoneNumberLineEdit.setPlaceholderText(_translate("MainWindow", "Пример: +79636521929"))
        self.editPasswordButton.setText(_translate("MainWindow", "Забыли пароль?"))
        self.paramConnectToDBButton.setText(_translate("MainWindow", "Параметры"))


def userTest(phoneNumber, password):
    from InputTest import userTest
    userTest(phoneNumber, password)


def editPassword():
    from Windows.QtWindows.resetPasswordWindow import showResetPasswordWindow
    showResetPasswordWindow()
    closeMainWindow()


def editParamConnectToDB():
    from Windows.QtWindows.inputParamToDB import showInputParamToDBWindow
    showInputParamToDBWindow()
    closeMainWindow()


def start():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    global MainWindow
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


def showMainWindow():
    global MainWindow
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()


def closeMainWindow():
    MainWindow.close()

