# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'okOrCancelWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_okOrCancelWindow(object):
    def setupUi(self, okOrCancelWindow):
        okOrCancelWindow.setObjectName("okOrCancelWindow")
        okOrCancelWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        okOrCancelWindow.resize(500, 200)
        okOrCancelWindow.setStyleSheet("background-color: rgb(212, 237, 255);")
        self.label = QtWidgets.QLabel(okOrCancelWindow)
        self.label.setGeometry(QtCore.QRect(20, 20, 460, 120))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText(massageText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.cancelButton = QtWidgets.QPushButton(okOrCancelWindow)
        self.cancelButton.setGeometry(QtCore.QRect(380, 150, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.cancelButton.setObjectName("cancelButton")
        self.okButton = QtWidgets.QPushButton(okOrCancelWindow)
        self.okButton.setGeometry(QtCore.QRect(250, 150, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.okButton.setObjectName("okButton")

        def closeOkWindow():
            okOrCancelWindow.close()
            from InputTest import replaceFileTest
            replaceFileTest(True, fileName)

        def closeCancelWindow():
            okOrCancelWindow.close()
            from InputTest import replaceFileTest
            replaceFileTest(False, fileName)

        self.okButton.clicked.connect(closeOkWindow)
        self.cancelButton.clicked.connect(closeCancelWindow)

        self.retranslateUi(okOrCancelWindow)
        QtCore.QMetaObject.connectSlotsByName(okOrCancelWindow)

    def retranslateUi(self, okOrCancelWindow):
        _translate = QtCore.QCoreApplication.translate
        okOrCancelWindow.setWindowTitle(_translate("okOrCancelWindow", "Warning"))
        self.cancelButton.setText(_translate("okOrCancelWindow", "Отмена"))
        self.okButton.setText(_translate("okOrCancelWindow", "Да"))


def showOkOrCancelWindow():
    global okOrCancelWindow
    okOrCancelWindow = QtWidgets.QDialog()
    ui = Ui_okOrCancelWindow()
    ui.setupUi(okOrCancelWindow)
    okOrCancelWindow.show()


def editTextAndFileName(text, name):
    global massageText
    massageText = text
    global fileName
    fileName = name
    showOkOrCancelWindow()
