# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statusWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_statusWindow(QtCore.QThread):
    def setupUi(self, statusWindow):
        statusWindow.setObjectName("statusWindow")
        statusWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        statusWindow.resize(500, 200)
        statusWindow.setStyleSheet("background-color: rgb(212, 237, 255);")
        self.statusLabel = QtWidgets.QLabel(statusWindow)
        self.statusLabel.setGeometry(QtCore.QRect(20, 20, 461, 161))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.statusLabel.setFont(font)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")

        self.statusLabel.setText(statusText)

    def retranslateUi(self, statusWindow):
        _translate = QtCore.QCoreApplication.translate
        statusWindow.setWindowTitle(_translate("statusWindow", "Загрузка"))
        self.statusLabel.setText(_translate("statusWindow", "TextLabel"))


def showStatusWindow():
    global statusWindow
    statusWindow = QtWidgets.QDialog()
    ui = Ui_statusWindow()
    ui.setupUi(statusWindow)
    statusWindow.show()


def closeStatusWindow():
    statusWindow.close()


def editStatusText(_statusText):
    global statusText
    statusText = _statusText
    showStatusWindow()
