# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableExtensionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QCheckBox, QHBoxLayout, QTableWidgetItem, QRadioButton, QButtonGroup
from PyQt5.QtCore import Qt


class Ui_tableExtensionWindow(object):
    def setupUi(self, tableExtensionWindow):
        tableExtensionWindow.setObjectName("tableExtensionWindow")
        tableExtensionWindow.setWindowModality(QtCore.Qt.NonModal)
        tableExtensionWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        tableExtensionWindow.setFont(font)
        tableExtensionWindow.setStyleSheet("background-color: rgb(212, 237, 255);")
        self.centralwidget = QtWidgets.QWidget(tableExtensionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hiLabel = QtWidgets.QLabel(self.centralwidget)
        self.hiLabel.setGeometry(QtCore.QRect(0, 0, 800, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.hiLabel.setFont(font)
        self.hiLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hiLabel.setAutoFillBackground(False)
        self.hiLabel.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.hiLabel.setText("")
        self.hiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hiLabel.setWordWrap(True)
        self.hiLabel.setObjectName("hiLabel")
        self.continueButton = QtWidgets.QPushButton(self.centralwidget)
        self.continueButton.setGeometry(QtCore.QRect(300, 540, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.continueButton.setFont(font)
        self.continueButton.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.continueButton.setDefault(False)
        self.continueButton.setFlat(False)
        self.continueButton.setObjectName("continueButton")
        self.tableExtensionWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableExtensionWidget.setGeometry(QtCore.QRect(0, 180, 800, 350))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.tableExtensionWidget.setFont(font)
        self.tableExtensionWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableExtensionWidget.setObjectName("tableExtensionWidget")
        self.tableExtensionWidget.setColumnCount(0)
        self.tableExtensionWidget.setRowCount(0)
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(0, 110, 800, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.infoLabel.setFont(font)
        self.infoLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.infoLabel.setAutoFillBackground(False)
        self.infoLabel.setStyleSheet("")
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setWordWrap(False)
        self.infoLabel.setObjectName("infoLabel")
        tableExtensionWindow.setCentralWidget(self.centralwidget)

        self.hiLabel.setText("Выгрузка документа")
        self.tableExtensionWidget.setRowCount(len(fileExtension))
        self.tableExtensionWidget.setColumnCount(2)
        self.tableExtensionWidget.setHorizontalHeaderLabels(('Добавить?', 'Расширение'))
        self.tableExtensionWidget.setColumnWidth(0, 100)
        self.tableExtensionWidget.setColumnWidth(1, 679)

        for i in range(len(fileExtension)):
            widget = QWidget()
            checkbox = QCheckBox()
            checkbox.setCheckState(Qt.Unchecked)
            layoutH = QHBoxLayout(widget)
            layoutH.addWidget(checkbox)
            layoutH.setAlignment(Qt.AlignCenter)
            layoutH.setContentsMargins(0, 0, 0, 0)
            self.tableExtensionWidget.setCellWidget(i, 0, widget)
            self.tableExtensionWidget.setItem(i, 1, QTableWidgetItem(fileExtension[i][1]))

        def clickedContinueButton():
            checkedList = []
            for i in range(self.tableExtensionWidget.rowCount()):
                if self.tableExtensionWidget.cellWidget(i, 0).findChild(type(QCheckBox())).isChecked():
                    checkedList.append(fileExtension[i][1])
            testCheckedList(checkedList)

        self.continueButton.clicked.connect(clickedContinueButton)

        self.retranslateUi(tableExtensionWindow)
        QtCore.QMetaObject.connectSlotsByName(tableExtensionWindow)

    def retranslateUi(self, tableExtensionWindow):
        _translate = QtCore.QCoreApplication.translate
        tableExtensionWindow.setWindowTitle(_translate("tableExtensionWindow", "Experiment"))
        self.continueButton.setText(_translate("tableExtensionWindow", "Продолжить"))
        self.infoLabel.setText(_translate("tableExtensionWindow", "Выберите желаемое расширение файла:"))


def showTableExtensionWindow():
    global tableExtensionWindow
    tableExtensionWindow = QtWidgets.QMainWindow()
    ui = Ui_tableExtensionWindow()
    ui.setupUi(tableExtensionWindow)
    tableExtensionWindow.show()


def closeTableExtensionWindow():
    tableExtensionWindow.close()


def editFileExtension(info):
    global fileExtension
    fileExtension = info


def testCheckedList(checkedList):
    if len(checkedList) > 0:
        from InputTest import tryToCreateDocument, editExtensionCheckedList
        editExtensionCheckedList(checkedList)
        tryToCreateDocument(None)
        closeTableExtensionWindow()
        from Windows.QtWindows.menuActionsWindow import showMenuActionsWindow
        showMenuActionsWindow()
    else:
        from Windows.QtWindows.errWindow import editText
        editText('Ошибка! Вы не выбрали ни одного расширения')
